

#include "/vmm/bin/common.defs"
#define VMX_PHASE 3
#if VMX_PHASE == 3
#include "/vmm/data/vmm-configs/common/vmxc/common.vmx.p3.defs"
#elif VMX_PHASE == 2
#include "/vmm/data/vmm-configs/common/vmxc/common.vmx.p2.defs"
#else
#include "/vmm/data/vmm-configs/common/vmxc/common.vmx.p1.defs"
#endif
#include "/homes/abstine/vmx-nested-macros/common.vjunos.defs"


#undef vjunos_switch_disk
#undef vjunos_router_disk

#define VROUTER_DISK basedisk "/vmm/data/base_disks/junos/vmx/vJunos-router-24.2R2-S1.6.qcow2";

##################################################################################

TOPOLOGY_START(VMM-LAB)

bridge "111__1aaeppss"{};
bridge "111__2aaeppss"{};
bridge "111__3aaeppss"{};



#undef VJUNOS_CHASSIS_NAME
#define VJUNOS_CHASSIS_NAME   vrouter1
   VJUNOS_CHASSIS_START()
      VJUNOS_START(vrouter1 , 0)
         VJUNOS_INSTANCE(vrouter1 , VROUTER_DISK, VJUNOS_PRODUCT_VMX, 0)
         VJUNOS_CONNECT(VJUNOS_GE(0,0,0), 111__1aaeppss)
         VJUNOS_CONNECT(VJUNOS_GE(0,0,1), 111__3aaeppss)
     VJUNOS_END
   VJUNOS_CHASSIS_END






#undef VJUNOS_CHASSIS_NAME
#define VJUNOS_CHASSIS_NAME   vrouter2
   VJUNOS_CHASSIS_START()
      VJUNOS_START(vrouter2 , 0)
         VJUNOS_INSTANCE(vrouter2 , VROUTER_DISK, VJUNOS_PRODUCT_VMX, 0)
         VJUNOS_CONNECT(VJUNOS_GE(0,0,0), 111__1aaeppss)
         VJUNOS_CONNECT(VJUNOS_GE(0,0,1), 111__2aaeppss)
     VJUNOS_END
   VJUNOS_CHASSIS_END






#undef VJUNOS_CHASSIS_NAME
#define VJUNOS_CHASSIS_NAME   vrouter3
   VJUNOS_CHASSIS_START()
      VJUNOS_START(vrouter3 , 0)
         VJUNOS_INSTANCE(vrouter3 , VROUTER_DISK, VJUNOS_PRODUCT_VMX, 0)
         VJUNOS_CONNECT(VJUNOS_GE(0,0,1), 111__2aaeppss)
         VJUNOS_CONNECT(VJUNOS_GE(0,0,0), 111__3aaeppss)
     VJUNOS_END
   VJUNOS_CHASSIS_END








PRIVATE_BRIDGES
TOPOLOGY_END